services:
  db:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: polychatdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SSL_CA: ""
      MYSQL_SSL_CERT: ""
      MYSQL_SSL_KEY: ""
      TZ: "Asia/Seoul"
    ports:
      - "13306:3306"
    volumes:
      - ./docker/polychatdb/mysql_data:/var/lib/mysql
      - ./docker/polychatdb/my.cnf:/etc/mysql/my.cnf

  nginx:
    image: nginx:latest
    container_name: nginx-polychat
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/certs:/etc/ssl/certs:ro
      - ./docker/nginx/private:/etc/ssl/private:ro
      - ./docker/nginx/static:/usr/share/nginx/html
#    extra_hosts:
#      - "host.docker.internal:host-gateway"  # Linux에서 호스트 접근을 위해 추가

networks:
  host:
    external: true

