#!/bin/bash

# Java를 다시 빌드 하고 실행

# 실행 중인 Java 서버 프로세스 찾기 및 종료
pid=$(pgrep -f 'polychat-server.jar')
if [ -n "$pid" ]; then
    echo "기존 서버 프로세스 종료 중... (PID: $pid)"
    kill -9 "$pid"
    echo "서버가 종료되었습니다."
else
    echo "실행 중인 서버 프로세스가 없습니다."
fi

# Gradle로 프로젝트 빌드
echo "프로젝트 빌드 중..."
./gradlew bootJar -x test

# 빌드가 성공하면 서버 실행
if [ $? -eq 0 ]; then
    echo "빌드 성공. 서버를 실행합니다..."
    log_file="$(date '+%Y-%m-%d_%H-%M-%S').log"
    nohup java -jar ./build/libs/polychat-server.jar > ./logs/"$log_file" 2>&1 &
    echo "서버가 실행되었습니다. 로그 파일명: $log_file"
    tail -f ./logs/"$log_file"
else
    echo "빌드 실패. 서버를 실행하지 않습니다."
fi
